<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="description" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>{% block title_full %}{% block title %}{% endblock %} - Idling in the EU{% endblock %}</title>

		<link href='http://fonts.googleapis.com/css?family=Marcellus+SC|Lora|Raleway:300' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="/styles/global.css">

		<link rel="icon" type="image/png" href="/images/favicon.png">
	</head>
	<body>

		{% block content %}{% endblock %}

		<script src="/scripts/global.js"></script>


		<!-- Google Analytics -->

	</body>
</html>